apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: flux-cluster
    app.kubernetes.io/part-of: flux
  name: flux-cluster
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-cluster
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: flux-cluster
  url: ssh://fluxpres@sshd.default:/home/fluxpres/flux-cluster.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-cluster
spec:
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
