# See https://kind.sigs.k8s.io/docs/user/configuration/
# kind create cluster --config kind-api-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30022
    hostPort: 30022
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
