apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd
spec:
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
        - name: sshd
          image: flux_sshd:v1
          ports:
            - containerPort: 2220
---
apiVersion: v1
kind: Service
metadata:
  name: sshd
  labels:
    app: sshd
spec:
  type : NodePort
  ports:
    - port : 22
      nodePort : 30022
      targetPort: 2220
      protocol : TCP
  selector:
    app: sshd
