name: 'Kustomize GitHub Actions'
on:
  - push
jobs:
  kustomize:
    name: 'Kustomize'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

        # https://github.com/karancode/kustomize-github-action
      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@v1.3.2
        with:
          kustomize_version: '5.3.0'
          kustomize_build_dir: 'flux/tenant'
          kustomize_comment: false
          kustomize_output_file: "/dev/null"
